# support insecure! thunks
insecure-entitlements = [ "security.insecure" ]

# configure bridge networking
[worker.oci]
networkMode = "cni"
cniConfigPath = "/etc/buildkit/bass.conflist"

[worker.containerd]
networkMode = "cni"
cniConfigPath = "/etc/buildkit/bass.conflist"
