name: pr-test

on:
  pull_request:
    branches: ["*"]

jobs:
  bass:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: {submodules: true}
    - uses: cachix/install-nix-action@v15
    - run: ./ci/pr-test
